from utils.exception.web_exception.django_exception.view_exception import ViewException


class ResponseException(ViewException):
    error_id = "86bbd4f1b3d84c61a2b2f3ed43cbc698"
