pyodbc.cpython-312-x86_64-linux-gnu.so,sha256=qWmf_tq36Voi27h9e2VAa-TcHLqMvENtAkh23HRRX8E,997585
pyodbc.pyi,sha256=SXkDoEs1fp-Ke4zaihF7fMoKi5LkfCwyAQ8f9FQ-vQg,32351
pyodbc-5.0.1.dist-info/top_level.txt,sha256=Rb69vS-SNN_Bfh99vX7eCcvEAJoyzowG3u4R7W36Flw,8
pyodbc-5.0.1.dist-info/WHEEL,sha256=4ZiCdXIWMxJyEClivrQv1QAHZpQh8kVYU92_ZAVwaok,152
pyodbc-5.0.1.dist-info/RECORD,,
pyodbc-5.0.1.dist-info/METADATA,sha256=TdjNaj5Jb_KAndh3xRlGgwKiKYA3QzpWCOdKn0xd5QM,2717
pyodbc-5.0.1.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
